### ISSUE TITLE
Summary: Needs attention

### ISSUE THREAD

**Issue by martoio** [mtubes/f1-3-c2p1-colmar-academy#8]
Not too sure what went wrong here. Did you run out of time or are you still fuzzy on some of the concepts around responsive design?

If you are unsure about responsive design:
https://www.youtube.com/watch?v=Wm6CUkswsNw
https://www.youtube.com/watch?v=RMg6t7MjIt8
https://www.youtube.com/playlist?list=PL4cUxeGkcC9g9Vh9MAA-XKnfJsWZnPZFw

Flexbox:
https://www.youtube.com/watch?v=G7EIAgfkhmg
https://www.youtube.com/watch?v=k32voqQhODc
https://www.youtube.com/watch?v=JJSoEo8JSnc
https://www.youtube.com/watch?v=qlA7dputiNc

That's a bunch of resources that should be able to point you in the right direction in terms of programming the website.

Best practices:
https://github.com/bendc/frontend-guidelines
http://learn.shayhowe.com/html-css/writing-your-best-code/

I would advise that you redo this project, because you are currently missing out on the main aspect of the exercise, which was the responsive design. The initial look is good for the most part, but aim to make it responsive.

If there's something specific that is bugging you or you aren't certain of, do use the Slack channels or leave a comment here so I can maybe point you towards some more relevant resources to plug in any gaps you might have in your understanding of the material.

**Comment by mtubes** [comment]
Thank you for the feedback! I've redone the project. I will upload it shortly. Have a great day!
